[model]
#name  = "arcee-ai/trinity-large-preview:free"
# name = "stepfun/step-3.5-flash:free"
# name = "nvidia/nemotron-3-super-120b-a12b:free"
# name = "nvidia/nemotron-3-nano-4b"
name = "trinity-nano-preview-mlx"
